import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat-app",
  description: "Generated by create next app",
  icons : {
    icon : "./fevicon.ico "
  }
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <Providers>
        <body className={inter.className}>{children}</body>
        </Providers>
      </html>
  );
}
