

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat-app",
  description: "Generated by create next app",
  icons : {
    icon : "./fevicon.ico "
  }
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}